######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/ptsa_logo.png"

logo_on_black: "/img/ptsa_logo.png"
custom_js: []
custom_css: 
  - "css/custom.css"

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

### donation link ###
donation_url: "YOUR_DONATION_URL_HERE"

### contact email ###
email: "info@slptsa.org"

github:
  repo_url: "https://github.com/klevermonicker/slptsa/blob/master"
  show_edit_link: false

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: ""
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
